### ISSUE TITLE
更新后，服务器信息栏框体的锚点似乎变为中间了

### ISSUE THREAD

**Issue by Annullare** [ottercorp/DalamudPluginsD17#132]
更新后，服务器信息栏的字数或者总长度发生变化时，框体会以中心为锚点发生长度改变，但开启并关闭界面设置后位置恢复“正常”
后面发现框体会以最后一次关闭界面设置后的状态将锚点置于当前框体的中心
正常
![1](https://github.com/ottercorp/Dalamud/assets/42252672/248e8a39-0f5e-4f01-939b-7d8c8ddd1148)
关闭界面设置后，随便加点什么，再打开
![2](https://github.com/ottercorp/Dalamud/assets/42252672/8d020666-a26c-4bc8-aa99-1ebf938ace8b)
关闭界面设置后再打开一次
![3](https://github.com/ottercorp/Dalamud/assets/42252672/3306992b-baed-427e-88af-57531e69033e)
这次是删点东西后
![4](https://github.com/ottercorp/Dalamud/assets/42252672/557baaf9-0e93-4866-acac-fbfe44436ddb)

**Comment by wozaiha** [comment]
是否打开了动态分辨率或类似的设置？

**Comment by Annullare** [comment]
没有打开

**Comment by Bluefissure** [comment]
请向 [Dalamud](https://github.com/ottercorp/Dalamud) 或 [上游Dalamud（国际服）](https://github.com/goatcorp/Dalamud) 提交 issue，这里是插件仓库。
