### ISSUE TITLE
artisan字体变化导致卫月和游戏崩溃

### ISSUE THREAD

**Issue by JackGeekF** [ottercorp/DalamudPluginsD17#204]
1.在卫月中直接打开artisan。界面字体和大小显示正常。
![WEXDOKRY{2VGLZ4R9G9Q74F](https://github.com/ottercorp/DalamudPluginsD17/assets/31602132/b67aea2c-1f9f-4a77-a81a-e423dd70a0d4)
![KF}}6EZT7NZ$XLH 342PG2K](https://github.com/ottercorp/DalamudPluginsD17/assets/31602132/eac0c979-9b65-49f8-9f6e-2af277e9fb27)
2.当在游戏内打开制作界面时，字体会变小。
![image](https://github.com/ottercorp/DalamudPluginsD17/assets/31602132/69e7a226-c6a1-43cd-a4a6-91db47fa9fdb)
同时卫月也发生了变化。
![image](https://github.com/ottercorp/DalamudPluginsD17/assets/31602132/d996a0d0-9b70-4fc7-9785-96cd6dcb15fd)
3.dang当在卫月的设置选项中点击保存更改时，字体变了回去，但是游戏也炸掉了。
![image](https://github.com/ottercorp/DalamudPluginsD17/assets/31602132/0514a0ab-9226-419b-879a-5ae9c8a35afd)

**Comment by wozaiha** [comment]
第三方请向作者反馈
