### ISSUE TITLE
Simple Tweaks插件部分功能性问题

### ISSUE THREAD

**Issue by zxwqwq** [ottercorp/DalamudPluginsD17#262]
1.服务器信息栏自定义时间格式后偏移出屏幕外
![image](https://github.com/user-attachments/assets/617a2f09-d21e-4078-a4c0-5b51bb1a08b7)
2.简洁跨界传送菜单不适配，超出框的内容都无法点击
![image](https://github.com/user-attachments/assets/4b93d43c-78ae-45c3-ac92-2ad2d0bcfdba)
3.市场版显示正在获取数据时自动刷新市场板的功能不适配
![image](https://github.com/user-attachments/assets/d365d535-e965-4478-82e1-98729f2ea25f)
4.常规设置中update translation按钮点击后报错
![image](https://github.com/user-attachments/assets/644183ab-36ba-43b1-91e6-bd383f5b6381)

**Comment by zhouhuichen741** [comment]
自定义部队也有问题,进本和在战场的时候会有个别人莫名其妙的有部队显示

**Comment by wozaiha** [comment]
1.自己拖一下，大概是feature
2.修了
3.sig飘了没找到
4.修过了
5.最近姓名版就这样子
