### ISSUE TITLE
accountant和deepDungeondex安装失败

### ISSUE THREAD

**Issue by zxwqwq** [ottercorp/DalamudPluginsD17#27]
log分别如图
![image](https://user-images.githubusercontent.com/83502581/209475924-256b9e34-8361-4edb-9d72-95bb6ec996ad.png)
![image](https://user-images.githubusercontent.com/83502581/209475935-e54b708f-e338-44ff-b241-652f20fb9fd3.png)

**Comment by wozaiha** [comment]
DDD这个看起来是网络问题，挂个梯子？

**Comment by zxwqwq** [comment]
DeepDungeonDex挂了梯子后仍然安装失败，去https://aonyx.ffxiv.wang/Plugin/PluginMaster下载了latest，使用开发版插件位置加载依旧失败，报错如图所示。（开梯子和关梯子都试过了，下载其他插件网络也正常）
![image](https://user-images.githubusercontent.com/83502581/209494087-9f554f12-5e5e-40fe-b566-eecc72dfc57c.png)
