### ISSUE TITLE
stp的多彩玩家名出问题了

### ISSUE THREAD

**Issue by DogeTwo** [ottercorp/DalamudPluginsD17#276]
在某次更新（至少距离现在也有一阵子了，7.0之前就存在的情况）
stp的 多彩玩家名 工具无法起作用，通常玩家名字都不会变色。但是在有玩家使用了一长串/em 某信息 中若带有别人的名字，则这一段话里会有完全错误的上色（颜色完全画歪到别的字上了）
该情况曾向stp主库发过issue但未被解决。似乎是国服库的特殊情况。

**Comment by wozaiha** [comment]
#277
