### ISSUE TITLE
[Test Issue] Character panel refined 乱码

### ISSUE THREAD

**Issue by MapleRecall** [ottercorp/DalamudPluginsD17#9]
乱码了好耶！(图片来自群友，侵删）
![image](https://user-images.githubusercontent.com/18360825/208648771-11b9f951-c439-4d5d-85bd-ef5565e8522c.png)

**Comment by wozaiha** [comment]
感觉是offset出错？

**Comment by Bluefissure** [comment]
不懂，之前是谁维护的来着（

**Comment by wozaiha** [comment]
请更新大喇叭
